In [6]:
import pandas as pd

homicidios = pd.read_csv("/content/Homicídios Mulheres_capitais.csv", sep=",")
taxa = pd.read_csv("/content/Taxa de Homicídios Mulheres_capitais.csv", sep=",")

# Deixa os nomes das colunas simples
homicidios.columns = ["periodo", "cod_ibge", "homicidios"]
taxa.columns = ["periodo", "cod_ibge", "taxa"]

# "1989-01-15T00:00:00.000Z" vira só o ano: 1989
homicidios["ano"] = pd.to_datetime(homicidios["periodo"]).dt.year
taxa["ano"] = pd.to_datetime(taxa["periodo"]).dt.year

print(homicidios.shape, taxa.shape)
homicidios.head()

(918, 4) (918, 4)

                    periodo  cod_ibge  homicidios   ano
0  1989-01-15T00:00:00.000Z   1100205          14  1989
1  1990-01-15T00:00:00.000Z   1100205          12  1990
2  1991-01-15T00:00:00.000Z   1100205          11  1991
3  1992-01-15T00:00:00.000Z   1100205          14  1992
4  1993-01-15T00:00:00.000Z   1100205          11  1993

In [7]:
capitais = {
    1100205: "Porto Velho", 1200401: "Rio Branco", 1302603: "Manaus",
    1400100: "Boa Vista", 1501402: "Belém", 1600303: "Macapá",
    1721000: "Palmas", 2111300: "São Luís", 2211001: "Teresina",
    2304400: "Fortaleza", 2408102: "Natal", 2507507: "João Pessoa",
    2611606: "Recife", 2704302: "Maceió", 2800308: "Aracaju",
    2927408: "Salvador", 3106200: "Belo Horizonte", 3205309: "Vitória",
    3304557: "Rio de Janeiro", 3550308: "São Paulo", 4106902: "Curitiba",
    4205407: "Florianópolis", 4314902: "Porto Alegre", 5002704: "Campo Grande",
    5103403: "Cuiabá", 5208707: "Goiânia", 5300108: "Brasília",
}

homicidios["capital"] = homicidios["cod_ibge"].map(capitais)
taxa["capital"] = taxa["cod_ibge"].map(capitais)

print("Códigos sem nome:", homicidios[homicidios["capital"].isna()]["cod_ibge"].unique())
homicidios.head()

Códigos sem nome: []

                    periodo  cod_ibge  homicidios   ano      capital
0  1989-01-15T00:00:00.000Z   1100205          14  1989  Porto Velho
1  1990-01-15T00:00:00.000Z   1100205          12  1990  Porto Velho
2  1991-01-15T00:00:00.000Z   1100205          11  1991  Porto Velho
3  1992-01-15T00:00:00.000Z   1100205          14  1992  Porto Velho
4  1993-01-15T00:00:00.000Z   1100205          11  1993  Porto Velho

In [8]:
print(taxa.dtypes)
taxa.head()

periodo      object
cod_ibge      int64
taxa        float64
ano           int32
capital      object
dtype: object

                    periodo  cod_ibge  taxa   ano      capital
0  1989-01-15T00:00:00.000Z   1100205  5.40  1989  Porto Velho
1  1990-01-15T00:00:00.000Z   1100205  4.40  1990  Porto Velho
2  1991-01-15T00:00:00.000Z   1100205  3.83  1991  Porto Velho
3  1992-01-15T00:00:00.000Z   1100205  5.07  1992  Porto Velho
4  1993-01-15T00:00:00.000Z   1100205  3.71  1993  Porto Velho

In [9]:
dados = homicidios.merge(
    taxa[["cod_ibge", "ano", "taxa"]],
    on=["cod_ibge", "ano"],
    how="left",
)
dados = dados[["ano", "cod_ibge", "capital", "homicidios", "taxa"]]

print(dados.shape)
print("Anos:", dados["ano"].min(), "a", dados["ano"].max())
print("Capitais:", dados["capital"].nunique())
print("Valores vazios por coluna:")
print(dados.isna().sum())
dados.head()

(918, 5)
Anos: 1989 a 2022
Capitais: 27
Valores vazios por coluna:
ano           0
cod_ibge      0
capital       0
homicidios    0
taxa          0
dtype: int64

    ano  cod_ibge      capital  homicidios  taxa
0  1989   1100205  Porto Velho          14  5.40
1  1990   1100205  Porto Velho          12  4.40
2  1991   1100205  Porto Velho          11  3.83
3  1992   1100205  Porto Velho          14  5.07
4  1993   1100205  Porto Velho          11  3.71

In [10]:
dados.to_csv("/content/capitais_homicidios_mulheres.csv", index=False)

# Etapa 1: Governança, Ética e Aquisição dos Dados
**Responsável:** Alana Caled

## 1. Origem dos dados
- **Fonte primária:** Sistema de Informações sobre Mortalidade (SIM), do Ministério da Saúde (MS/SVSA)
- **Plataforma de acesso:** Atlas da Violência, do IPEA e do Fórum Brasileiro de Segurança Pública (FBSP)
- **Link:** https://www.ipea.gov.br/atlasviolencia/tema/61/
- **Tema:** Violência por Gênero
- **Séries utilizadas:** "Homicídios Mulheres" e "Taxa de Homicídios Mulheres"
- **Recorte:** 27 capitais brasileiras
- **Período:** 1989 a 2022 (dados anuais)
- **Formato:** CSV
- **Data do download:** 18/10/2026
- **Metadados:** disponíveis na página de cada série no Atlas da Violência (ícone de documento)

## 2. Dicionário de dados
Tabela final: `capitais_homicidios_mulheres.csv`

| Coluna | Descrição |
| :--- | :--- |
| ano | Ano de referência dos dados |
| cod_ibge | Código IBGE do município (7 dígitos) |
| capital | Nome da capital (incluído pela equipe a partir do código IBGE) |
| homicidios | Número de mulheres vítimas de homicídio no ano |
| taxa | Homicídios de mulheres para cada 100 mil mulheres |

## 3. Observações da coleta
- Os recortes por UF e por município apresentaram erro no site ("Nenhum dado disponível para download"). Por isso, a equipe utilizou o recorte por capitais.
- O site informa que os arquivos usam ponto e vírgula como separador, mas os arquivos baixados vieram separados por vírgula.
- A coluna de data vinha no formato "1989-01-15T00:00:00.000Z" e foi convertida apenas para o ano.
- As duas séries foram unidas em uma única tabela usando o código IBGE e o ano.

## 4. Qualidade inicial
- 918 registros: 27 capitais x 34 anos (1989 a 2022).
- Nenhum valor ausente nas colunas.
- Todos os códigos IBGE corresponderam a uma capital.

## 5. Licença de uso
Os dados são públicos e divulgados gratuitamente pelo IPEA e pelo FBSP na plataforma Atlas da Violência, a partir do Sistema de Informações sobre Mortalidade (SIM) do Ministério da Saúde. A equipe utiliza os dados apenas para fins acadêmicos, sempre citando as fontes.

## 6. LGPD e ética
- Os dados são agregados por capital e por ano.
- Não há nenhuma informação que identifique uma pessoa (nome, CPF, endereço ou idade individual).
- Por isso, o uso desta base é compatível com a Lei Geral de Proteção de Dados (Lei nº 13.709/2018).
- A equipe não coleta nem utiliza dados reais de usuárias do aplicativo. Os testes usam apenas personas fictícias.

## 7. Limitações
- **Registro da causa da morte:** algumas mortes violentas são registradas como "causa indeterminada" e não entram na contagem de homicídios. Por isso, o número real tende a ser maior.
- **Recorte geográfico:** os dados das capitais não representam o interior dos estados.
- **Indisponibilidade:** os recortes por UF e por município não estavam disponíveis para download na data da coleta.
- **Tipo de violência:** a base trata apenas de homicídios e não inclui agressões, ameaças ou violência psicológica.
- **Mudança de classificação:** de 1979 a 1995 os homicídios eram identificados pela CID-9 (códigos E960 a E978). A partir de 1996 passou a ser usada a CID-10. Por isso, comparações entre períodos antes e depois de 1996 devem ser feitas com cuidado.

## 8. Aviso
Qualquer indicador gerado a partir destes dados é uma estimativa acadêmica e **não substitui** atendimento policial, médico ou jurídico.

Em caso de emergência:
- **Ligue 180:** Central de Atendimento à Mulher (gratuito, 24h)
- **190:** Polícia Militar

# Etapa 2: Análise Exploratória dos Dados (EDA)
**Responsável:** Felipe Trindade

A análise exploratória investiga as características essenciais das duas variáveis numéricas do estudo:
- `homicidios`: contagem absoluta de mulheres vítimas de homicídio registradas em cada capital por ano.
- `taxa`: taxa de homicídios calculada por 100 mil habitantes do sexo feminino.

---

## 2.1 Medidas de Tendência Central e Dispersão
O cálculo das estatísticas descritivas básicas permite compreender a concentração dos dados e o nível de variabilidade das ocorrências entre as 27 capitais brasileiras ao longo dos 34 anos de registros (1989 a 2022).

In [ ]:
# Cálculo das Medidas Descritivas e Dispersão
vars_num = ["homicidios", "taxa"]

tabela_descritiva = pd.DataFrame({
    "Média": dados[vars_num].mean(),
    "Mediana": dados[vars_num].median(),
    "Moda": [dados["homicidios"].mode()[0], dados["taxa"].mode()[0]],
    "Desvio Padrão": dados[vars_num].std(),
    "Variância": dados[vars_num].var(),
    "Mínimo": dados[vars_num].min(),
    "Máximo": dados[vars_num].max(),
    "Amplitude": dados[vars_num].max() - dados[vars_num].min()
})

tabela_descritiva.round(2)

### Interpretação dos Resultados

1. **Tendência Central (Média, Mediana e Moda):**
   - **Homicídios (absoluto):** A média de homicídios é de **38,42**, enquanto a mediana é de **20,00** e a moda é **12,00**. O fato de a média ser substancialmente superior à mediana evidencia uma forte **assimetria positiva (à direita)**. Isso ocorre porque metrópoles de grande porte populacional (como São Paulo e Rio de Janeiro) registram centenas de casos por ano, puxando a média para cima, enquanto a maioria das capitais registra valores menores.
   - **Taxa por 100 mil habitantes:** A média da taxa é de **4,19** e a mediana é de **3,79**. A proximidade entre a média e a mediana demonstra que a taxa proporcional é uma métrica mais estável e representativa da realidade epidemiológica do que os números absolutos, controlando o efeito da escala populacional. A moda 0,00 reflete anos iniciais sem ocorrências registradas em capitais recém-criadas ou menores.

2. **Dispersão (Desvio Padrão, Variância e Amplitude):**
   - **Homicídios (absoluto):** O desvio padrão de **55,67** e a amplitude de **477,00** (variando de 0 a 477) refletem a heterogeneidade das capitais do país em tamanho de população. A variância amostral é expressiva (3.099,65).
   - **Taxa por 100 mil habitantes:** O desvio padrão é de **2,40** com amplitude de **18,59** (mínimo de 0,00 e máximo de 18,59). Essa amplitude acentuada na taxa indica que, mesmo controlando a população, existem capitais e anos específicos onde o risco de letalidade violenta contra a mulher foi mais de quatro vezes superior à média nacional.

Esses achados fundamentam a necessidade de focar as análises comparativas e os futuros modelos preditivos na **taxa proporcional**, e não apenas no volume absoluto.